name: Monitoring and Maintenance

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/monitoring.yml'

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Check for dependency updates
      run: |
        echo "Checking for outdated dependencies..."
        
        # Check root dependencies
        echo "=== Root Dependencies ==="
        npm outdated || echo "No outdated root dependencies found"
        
        # Check client dependencies
        echo "=== Client Dependencies ==="
        cd client && npm outdated || echo "No outdated client dependencies found"
        cd ..
        
        # Check server dependencies
        echo "=== Server Dependencies ==="
        cd server && npm outdated || echo "No outdated server dependencies found"
    
    - name: Security audit all packages
      run: |
        echo "Running security audits..."
        
        # Audit root
        echo "=== Root Security Audit ==="
        npm audit --audit-level moderate || echo "Root security audit completed"
        
        # Audit client
        echo "=== Client Security Audit ==="
        cd client && npm audit --audit-level moderate || echo "Client security audit completed"
        cd ..
        
        # Audit server
        echo "=== Server Security Audit ==="
        cd server && npm audit --audit-level moderate || echo "Server security audit completed"
        cd ..
    
    - name: Generate dependency report
      run: |
        echo "# Dependency Report - $(date)" > dependency-report.md
        echo "" >> dependency-report.md
        echo "## Outdated Packages" >> dependency-report.md
        echo "" >> dependency-report.md
        echo "### Root" >> dependency-report.md
        npm outdated --json > root-outdated.json 2>/dev/null || echo "{}" > root-outdated.json
        echo '```json' >> dependency-report.md
        cat root-outdated.json >> dependency-report.md
        echo '```' >> dependency-report.md
        echo "" >> dependency-report.md
        
        echo "### Client" >> dependency-report.md
        cd client && npm outdated --json > ../client-outdated.json 2>/dev/null || echo "{}" > ../client-outdated.json
        cd ..
        echo '```json' >> dependency-report.md
        cat client-outdated.json >> dependency-report.md
        echo '```' >> dependency-report.md
        echo "" >> dependency-report.md
        
        echo "### Server" >> dependency-report.md
        cd server && npm outdated --json > ../server-outdated.json 2>/dev/null || echo "{}" > ../server-outdated.json
        cd ..
        echo '```json' >> dependency-report.md
        cat server-outdated.json >> dependency-report.md
        echo '```' >> dependency-report.md
        
        echo "Dependency report generated"

  performance-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        echo "Installing root dependencies..."
        npm ci
        cd client && npm ci
        echo "Installing server dependencies..."
        cd ../server && npm ci
        echo "Dependencies installed successfully"
    
    - name: Build and performance test
        set -euo pipefail
        mkdir -p tmp
        trap 'echo "\n--- Performance server log ---"; cat tmp/perf-server.log || true' ERR

        echo "Building client for performance testing..."
        cd client
        npm run build
        cd ..

        echo "Starting server for performance testing..."
        cd server
        npm start > ../tmp/perf-server.log 2>&1 &
        SERVER_PID=$!
        echo "Server started with PID: $SERVER_PID"
        echo $SERVER_PID > ../tmp/perf-server.pid
        cd ..

        echo "Waiting for server to become ready..."
        READY=false
        for attempt in {1..12}; do
          if curl -sSf http://localhost:5000/api/health > /dev/null 2>&1; then
            echo "Server is responding (attempt $attempt)"
            READY=true
            break
          fi

          if ! ps -p $(cat tmp/perf-server.pid) > /dev/null; then
            echo "Server process exited prematurely"
            cat tmp/perf-server.log || true
            exit 1
          fi

          echo "Server not ready yet (attempt $attempt), retrying in 5s..."
          sleep 5
        done

        if [ "$READY" = false ]; then
          echo "Server did not become ready in time"
          exit 1
        fi

        echo "Running performance tests..."
        echo "1. Review dependency updates regularly" >> health-report.md
        echo "2. Monitor API response times" >> health-report.md
        echo "3. Check error logs for patterns" >> health-report.md
        echo "4. Update security patches promptly" >> health-report.md
        echo "" >> health-report.md
        echo "## Next Actions" >> health-report.md
        echo "- [ ] Review outdated dependencies" >> health-report.md
        echo "- [ ] Address any security vulnerabilities" >> health-report.md
        echo "- [ ] Optimize slow API endpoints if found" >> health-report.md
        echo "- [ ] Update documentation if needed" >> health-report.md
        
        echo "System health report generated"
    
    - name: Archive reports
      uses: actions/upload-artifact@v3
      with:
        name: monitoring-reports
        path: |
          health-report.md
          dependency-report.md
        retention-days: 30

  automated-maintenance:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' # Only run on scheduled triggers
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Automated maintenance tasks
      run: |
        echo "Running automated maintenance tasks..."
        
        # Clean up old log files (if any)
        echo "Cleaning up temporary files..."
        find . -name "*.log" -mtime +7 -delete 2>/dev/null || true
        find . -name "*.tmp" -mtime +1 -delete 2>/dev/null || true
        
        # Check disk usage
        echo "Checking disk usage..."
        df -h
        
        # Check for large files
        echo "Checking for large files..."
        find . -size +10M -type f -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null || echo "No large files found"
        
        echo "Automated maintenance completed"
    
    - name: Database maintenance
      run: |
        echo "Running database maintenance..."
        cd server
        
        # Install dependencies
        echo "Installing server dependencies..."
        npm ci
        
        # Start server briefly to trigger any migrations
        echo "Starting server briefly to trigger migrations..."
        timeout 30s npm start || echo "Server started and stopped for migration check"
        
        # Check database size
        echo "Checking for database file..."
        if [ -f "well_data.db" ]; then
          echo "Database size:"
          ls -lh well_data.db
        else
          echo "Database file not found"
        fi
        
        echo "Database maintenance completed"